# Generated by Django 5.0.1 on 2024-01-25 18:43

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
            managers=[
                ('objects', mainapp.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customsession',
            managers=[
                ('objects', mainapp.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('permissions', models.ManyToManyField(to='mainapp.custompermission')),
            ],
            managers=[
                ('objects', mainapp.models.CustomUserManager()),
            ],
        ),
    ]
