# Generated by Django 5.0.1 on 2024-02-01 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_custompermission_alter_customsession_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
