# Generated by Django 5.0.1 on 2024-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_customrole_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
