# Generated by Django 5.0.1 on 2024-02-01 16:01

import mainapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_custompermission_title_alter_customrole_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', mainapp.models.CustomUserManager()),
            ],
        ),
    ]
