# Generated by Django 5.0.1 on 2024-02-06 14:52

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_book_authors_alter_customrole_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('objects', mainapp.models.CustomUserManager()),
            ],
        ),
    ]
